### PR TITLE
[hrpsys_gazebo_general] revert default value of robot_hrpsys_bringup.launch and add test

### PR DESCRIPTION
**Pull request by Naoki-Hiraoka**
https://github.com/start-jsk/rtmros_gazebo/pull/250 accidentally changed the default value of robot_hrpsys_bringup.launch.
This PR revert the default value.

### CODE REVIEW

**Comment by pazeshun** [comment]
Perhaps you have to re-check if https://github.com/start-jsk/rtmros_tutorials/pull/568 works fix it, because `HRPSYS_RATE` is not specified in hrpsys_gazebo_tutorials:
https://github.com/start-jsk/rtmros_tutorials/blob/7dc73f471347af969570b5a675fcafe092434469/hrpsys_gazebo_tutorials/launch/hrp2jsk_hrpsys_bringup.launch#L18-L24
Also, its `iob_rate` sometimes seems 250:
https://github.com/start-jsk/rtmros_tutorials/blob/7dc73f471347af969570b5a675fcafe092434469/hrpsys_gazebo_tutorials/config/HRP2JSK.yaml#L5

**Comment by pazeshun** [comment]
@k-okada Could you review this?

**Comment by pazeshun** [comment]
@k-okada Kindly ping

**Comment by k-okada** [comment]
if we can catch this situation, just by "rostopic echo hz", please consider adding test. Or because if hrpsys, it is  hard to write good test for this?

**Comment by Naoki-Hiraoka** [comment]
I added tests for `kinetic` and `melodic`.

These tests check
- topic hz
- follow_joint_trajectory_action
- walk(Autobalancer + Stailizer)

**Comment by pazeshun** [comment]
@Naoki-Hiraoka Very nice!!!!
Why did indigo test fail?
Due to https://github.com/start-jsk/rtmros_gazebo/pull/253#issuecomment-627232994?
> But original indigo environment itself may be incorrect,
because it uses hrpsys_ros_bridge/models/SampleRobot.RobotHardware.conf which is written as exec_cxt.periodic.rate: 500.

**Comment by pazeshun** [comment]
My previous comment was just out of curiosity.
Anyway, testing `kinetic` and `melodic` seems enough.

**Comment by Naoki-Hiraoka** [comment]
> Why did indigo test fail?
> Due to [#253 (comment)](https://github.com/start-jsk/rtmros_gazebo/pull/253#issuecomment-627232994)?

I'm sorry but I don't know.
On indigo, Walk test failed here
https://github.com/Naoki-Hiraoka/rtmros_gazebo/blob/f32da243cb8aade0126e01b48d359424412bd09c/hrpsys_gazebo_general/test/test-samplerobot.py#L166

**Comment by pazeshun** [comment]
OK, thanks for reply.
@k-okada Could you review this?

**Pull request merged**
